[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/kr/pretty"
  branch = "master"

[[constraint]]
  name = "github.com/nats-io/go-nats-streaming"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.4.1"
