// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: account_create_operation.proto

/*
Package steempb is a generated protocol buffer package.

It is generated from these files:
	account_create_operation.proto
	account_create_with_delegation_operation.proto
	account_update_operation.proto
	account_witness_proxy_operation.proto
	account_witness_vote_operation.proto
	author_reward_operation.proto
	authority.proto
	block_operations.proto
	cancel_tranfer_from_savings_operation.proto
	challenge_authority_operation.proto
	change_recovery_account_operation.proto
	claim_reward_balance_operation.proto
	comment_benefactor_reward_operation.proto
	comment_operation.proto
	comment_options_operation.proto
	comment_payout_update_operation.proto
	comment_reward_operation.proto
	convert_operation.proto
	curation_reward_operation.proto
	custom_binary_operation.proto
	custom_json_operation.proto
	custom_operation.proto
	decline_voting_rights_operation.proto
	delegate_vesting_shares_operation.proto
	delete_comment_operation.proto
	escrow_approve_operation.proto
	escrow_dispute_operation.proto
	escrow_release_operation.proto
	escrow_transfer_operation.proto
	feed_publish_operation.proto
	fill_convert_request_operation.proto
	fill_order_operation.proto
	fill_transfer_from_savings_operation.proto
	fill_vesting_withdraw_operation.proto
	hardfork_operation.proto
	interest_operation.proto
	limit_order_cancel_operation.proto
	limit_order_create2_operation.proto
	limit_order_create_operation.proto
	liquidity_reward_operation.proto
	operation.proto
	operation_object.proto
	pow2_operation.proto
	pow_operation.proto
	price.proto
	producer_reward_operation.proto
	prove_authority_operation.proto
	recover_account_operation.proto
	report_over_production_operation.proto
	request_account_recovery_operation.proto
	reset_account_operation.proto
	return_vesting_delegation_operation.proto
	set_reset_account_operation.proto
	set_withdraw_vesting_route_operation.proto
	shutdown_witness_operation.proto
	transfer_from_savings_operation.proto
	transfer_operation.proto
	transfer_to_savings_operation.proto
	transfer_to_vesting_operation.proto
	vote_operation.proto
	withdraw_vesting_operation.proto
	witness_update_operation.proto

It has these top-level messages:
	AccountCreateOperation
	AccountCreateWithDelegationOperation
	AccountUpdateOperation
	AccountWitnessProxyOperation
	AccountWitnessVoteOperation
	AuthorRewardOperation
	Authority
	BlockOperations
	CancelTransferFromSavingsOperation
	ChallengeAuthorityOperation
	ChangeRecoveryAccountOperation
	ClaimRewardBalanceOperation
	CommentBenefactorRewardOperation
	CommentOperation
	CommentOptionsOperation
	CommentOptionsExtensions
	CommentPayoutBeneficiaries
	CommentPayoutUpdateOperation
	CommentRewardOperation
	ConvertOperation
	CurationRewardOperation
	CustomBinaryOperation
	CustomJSONOperation
	CustomOperation
	DeclineVotingRightsOperation
	DelegateVestingSharesOperation
	DeleteCommentOperation
	EscrowApproveOperation
	EscrowDisputeOperation
	EscrowReleaseOperation
	EscrowTransferOperation
	FeedPublishOperation
	FillConvertRequestOperation
	FillOrderOperation
	FillTransferFromSavingsOperation
	FillVestingWithdrawOperation
	HardforkOperation
	InterestOperation
	LimitOrderCancelOperation
	LimitOrderCreate2Operation
	LimitOrderCreateOperation
	LiquidityRewardOperation
	Operation
	OperationObject
	POW2Operation
	POWOperation
	Price
	ProducerRewardOperation
	ProveAuthorityOperation
	RecoverAccountOperation
	ReportOverProductionOperation
	RequestAccountRecoveryOperation
	ResetAccountOperation
	ReturnVestingDelegationOperation
	SetResetAccountOperation
	SetWithdrawVestingRouteOperation
	ShutdownWitnessOperation
	TransferFromSavingsOperation
	TransferOperation
	TransferToSavingsOperation
	TransferToVestingOperation
	VoteOperation
	WithdrawVestingOperation
	WitnessUpdateOperation
*/
package steempb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AccountCreateOperation struct {
}

func (m *AccountCreateOperation) Reset()         { *m = AccountCreateOperation{} }
func (m *AccountCreateOperation) String() string { return proto.CompactTextString(m) }
func (*AccountCreateOperation) ProtoMessage()    {}
func (*AccountCreateOperation) Descriptor() ([]byte, []int) {
	return fileDescriptorAccountCreateOperation, []int{0}
}

func init() {
	proto.RegisterType((*AccountCreateOperation)(nil), "steemwatch.steem.AccountCreateOperation")
}

func init() {
	proto.RegisterFile("account_create_operation.proto", fileDescriptorAccountCreateOperation)
}

var fileDescriptorAccountCreateOperation = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0x89, 0x4f, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x8d, 0xcf, 0x2f, 0x48, 0x2d, 0x4a,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x28, 0x2e, 0x49, 0x4d,
	0xcd, 0x2d, 0x4f, 0x2c, 0x49, 0xce, 0xd0, 0x03, 0x33, 0x95, 0x24, 0xb8, 0xc4, 0x1c, 0x21, 0x7a,
	0x9c, 0xc1, 0x5a, 0xfc, 0x61, 0x3a, 0x9c, 0x38, 0xa3, 0xd8, 0xc1, 0x4a, 0x0a, 0x92, 0x92, 0xd8,
	0xc0, 0xba, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32, 0xf0, 0x03, 0x1f, 0x5f, 0x00, 0x00,
	0x00,
}
